from fastapi import FastAPI, Depends
from app.database import test_connection, engine
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from app.models import Base
# Routers
from app.routers import auth, chat, admin, connections

# Generate database tables if they do not exist
try:
    Base.metadata.create_all(bind=engine)
except Exception as e:
    print("Could not build tables:", e)

from app.explanation import generate_explanation

app = FastAPI(title="Enterprise Multi-Agent NL2SQL Assistant (Upgraded)")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # for deployment
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(chat.router)
app.include_router(admin.router)
app.include_router(connections.router)

# Data Feed API (generated by Claude)
try:
    from app.routers.admin_data_routes import router as data_router
    app.include_router(data_router)
except ImportError:
    print("WARNING: app.routers.admin_data_routes not found or failed to load. The Data Feed endpoints will be unavailable.")

class QueryRequest(BaseModel):
    question: str

@app.get("/")
def root():
    return {"message": "Backend is running"}

@app.get("/health")
@app.head("/health")
def health():
    return {"status": "ok"}


@app.get("/test-db")
def test_db():
    db_name, user_name = test_connection()
    return {
        "status": "success",
        "database": db_name,
        "user": user_name,
    }
